"""Frozen forms for verb families whose analogs are generated by a transformation.

`fixtures/pt_frozen_forms.json` was captured from hand-authored, reviewed
verb files. It pins every cell so that moving a family's forms into a
transformation (or refactoring one) can't silently change what the cards
show.
"""

import json
import unittest
from pathlib import Path

from kofiish.main import load_resolved_verbs


FIXTURE = Path(__file__).parent / "fixtures" / "pt_frozen_forms.json"


class FrozenFormsTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _, _, verbs = load_resolved_verbs("pt")
        cls.resolved = {}
        for verb in verbs.values():
            cls.resolved[verb.lemma] = verb.forms
            cls.resolved.update(verb.analogs)
        cls.expected = json.loads(FIXTURE.read_text(encoding="utf-8"))

    def test_every_frozen_form_is_unchanged(self):
        for lemma, tenses in self.expected.items():
            self.assertIn(lemma, self.resolved, f"{lemma} is no longer resolved")
            for tense_name, forms in tenses.items():
                with self.subTest(lemma=lemma, tense=tense_name):
                    self.assertEqual(self.resolved[lemma][tense_name], forms)


if __name__ == "__main__":
    unittest.main()
